# Where things are
source              : .
destination         : ./_site
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Plugins
whitelist           : []
plugins             : []

timezone: "Asia/Jakarta"
markdown: kramdown
highlighter: rouge
#permalink: /berita/:year/:title/
paginate: 5

navbar-links:
  Beranda: "#BERANDA"
  Berita: /berita/
  Tentang: "#TENTANG"
  Fitur: "#FITUR"
  Pemasangan: "#PEMASANGAN"
  Unduh: "#UNDUH"
  Sponsor: "#SPONSOR"
  #Menjadi Sponsor: "/menjadi-sponsor.html"
  Bergabung: "https://github.com/BlankOn/wiki/blob/master/Memulai.md"
